[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "math-verify"
version = "0.1.0"
description = "A library for verifying mathematical answers"
authors = [
    { name = "Hynek Kydlíček", email = "hynek.kydlicek@huggingface.co" }
]
dependencies = [
    "sympy",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=22.0",
    "flake8>=4.0",
]

inference = [
    "lighteval[accelerate,vllm]",
]

# For the local package dependency
[tool.setuptools]
packages = ["latex2sympy2_extended_cloned"]

# Reference the local package
[tool.setuptools.package-dir]
latex2sympy2_extended_cloned = "./latex2sympy2_extended_cloned"